version = 0.1

[default.deploy.parameters]
stack_name = "time-tracker-sam-app"
resolve_s3 = true
s3_prefix = "time-tracker-sam-app"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TimeTrackerTableName=\"time-tracker-v2\" AllowedOrigins=\"http://localhost:5173,http://localhost:5174,https://dxvboogtj4a4b.cloudfront.net\""
image_repositories = []

[default.global.parameters]
region = "us-east-2"
